import type {
  DlcDraft,
  FichaOverlay,
  LanguageTrack,
  PcSpecs,
  SpecSheet,
  StoreDraft,
} from "@/lib/games/ficha";

function lang(
  name: string,
  interfaceOn: boolean,
  audio: boolean,
  subtitles: boolean,
): LanguageTrack {
  return { name, interface: interfaceOn, audio, subtitles };
}

const PT_FULL = lang("Português (Brasil)", true, true, true);
const PT_SUBS = lang("Português (Brasil)", true, false, true);
const PT_UI = lang("Português (Brasil)", true, false, false);
const EN = lang("Inglês", true, true, true);
const ES_LATAM = lang("Espanhol (América Latina)", true, true, true);
const ES_LATAM_SUBS = lang("Espanhol (América Latina)", true, false, true);
const ES_ES = lang("Espanhol (Espanha)", true, false, true);
const FR = lang("Francês", true, true, true);
const FR_SUBS = lang("Francês", true, false, true);
const DE = lang("Alemão", true, true, true);
const DE_SUBS = lang("Alemão", true, false, true);
const IT_SUBS = lang("Italiano", true, false, true);
const JP = lang("Japonês", true, true, true);
const ZH = lang("Chinês simplificado", true, false, true);
const KO = lang("Coreano", true, false, true);
const RU = lang("Russo", true, false, true);
const PL = lang("Polonês", true, false, true);

const WESTERN = [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, IT_SUBS];
const WESTERN_DUB = [PT_FULL, EN, ES_LATAM, FR, DE, IT_SUBS];
const AAA_PLUS = [...WESTERN_DUB, JP, ZH, KO, RU, PL];
const LIVE_OPS = [PT_FULL, EN, ES_LATAM, FR, DE, ZH, KO, JP, RU];

function sheet(
  os: string,
  cpu: string,
  gpu: string,
  ram: string,
  storage: string,
): SpecSheet {
  return { os, cpu, gpu, ram, storage };
}

function pc(minimum: SpecSheet, recommended: SpecSheet, note?: string): PcSpecs {
  return { minimum, recommended, note };
}

const WIN10 = "Windows 10 64-bit";
const WIN11 = "Windows 10/11 64-bit";

const SPEC_INDIE = pc(
  sheet(WIN10, "Intel Core i5-2300 / AMD FX-4350", "GTX 660 / Radeon HD 7870", "8 GB", "20 GB"),
  sheet(WIN10, "Intel Core i7-4790 / Ryzen 5 1600", "GTX 1060 / RX 580", "16 GB", "SSD 20 GB"),
);

const SPEC_SOULS = pc(
  sheet(WIN10, "Intel Core i5-8400 / Ryzen 3 3300X", "GTX 1060 3GB / RX 580 4GB", "12 GB", "60 GB"),
  sheet(WIN10, "Intel Core i7-8700K / Ryzen 5 3600X", "GTX 1070 / RX Vega 56", "16 GB", "SSD 60 GB"),
);

const SPEC_OPEN = pc(
  sheet(WIN10, "Intel Core i5-4670K / AMD FX-9590", "GTX 780 / Radeon R9 290", "8 GB", "70 GB"),
  sheet(WIN10, "Intel Core i7-4790 / Ryzen 5 1600", "GTX 1060 6GB / RX 480", "16 GB", "SSD 70 GB"),
);

const SPEC_MODERN = pc(
  sheet(WIN10, "Intel Core i7-6700 / Ryzen 5 1600", "GTX 1060 6GB / RX 580", "12 GB", "70 GB SSD"),
  sheet(WIN10, "Intel Core i7-12700 / Ryzen 7 5800X", "RTX 3070 / RX 6800 XT", "16 GB", "SSD NVMe 100 GB"),
);

const SPEC_UE5 = pc(
  sheet(WIN10, "Intel Core i7-8700 / Ryzen 5 3600", "GTX 1070 / RX 5700", "16 GB", "100 GB SSD"),
  sheet(WIN11, "Intel Core i7-12700K / Ryzen 7 5800X3D", "RTX 4070 / RX 7800 XT", "32 GB", "SSD NVMe 150 GB"),
);

function stores(...kinds: StoreDraft["kind"][]): StoreDraft[] {
  return kinds.map((kind) => ({ kind }));
}

function dlc(name: string, blurb: string, ...kinds: StoreDraft["kind"][]): DlcDraft {
  return { name, blurb, stores: stores(...kinds) };
}

const LIVE: FichaOverlay["dlcs"] = "live";
const NONE: FichaOverlay["dlcs"] = "none";

/**
 * Flagship cabinets get the full dossier. Titles missing here still infer
 * loja from platforms + Steam app id — just without min/rec, idioma e DLC.
 */
export const FICHA_BY_SLUG: Record<string, FichaOverlay> = {
  "the-witcher-3-wild-hunt": {
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    ageRating: "18",
    releaseDate: "19 mai 2015",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "gog", "playstation", "xbox", "nintendo"),
    pcSpecs: pc(
      sheet("Windows 7 64-bit", "Intel Core i5-2500K / AMD Phenom II X4 940", "GTX 660 / Radeon HD 7870", "6 GB", "35 GB"),
      sheet(WIN10, "Intel Core i7-3770 / AMD FX-8350", "GTX 770 / Radeon R9 290", "8 GB", "50 GB SSD"),
      "Next-gen update pede SSD. A Complete Edition já vem com os dois DLCs.",
    ),
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, PL, RU, ZH],
    dlcs: [
      dlc("Hearts of Stone", "Contrato curto e denso. A casa trata como obrigatório.", "steam", "gog"),
      dlc("Blood and Wine", "Toussaint inteira. Quase um segundo game.", "steam", "gog"),
    ],
    playModes: { offline: true, note: "Singleplayer. Sem loja no progresso." },
  },
  "elden-ring": {
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    ageRating: "16",
    releaseDate: "25 fev 2022",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_SOULS,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, IT_SUBS, JP, ZH, KO],
    dlcs: [
      dlc(
        "Shadow of the Erdtree",
        "A expansão. Mapa novo, chefes novos. A platina de verdade mora aqui.",
        "steam",
        "playstation",
        "xbox",
      ),
    ],
    playModes: {
      offline: true,
      coop: "Convocação opcional",
      multiplayer: "Invasão opcional",
      note: "Dá pra zerar 100% offline. O online é tempero, não trava.",
    },
  },
  "red-dead-redemption-2": {
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    ageRating: "18",
    releaseDate: "26 out 2018",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "launcher", "playstation", "xbox"),
    pcSpecs: pc(
      sheet(WIN10, "Intel Core i5-2500K / AMD FX-6300", "GTX 770 2GB / Radeon R9 280", "8 GB", "150 GB"),
      sheet(WIN10, "Intel Core i7-4770K / Ryzen 5 1500X", "GTX 1060 6GB / RX 480 4GB", "12 GB", "150 GB SSD"),
      "Launcher da Rockstar. SSD muda a vida no faroeste.",
    ),
    languages: WESTERN_DUB,
    dlcs: NONE,
    dlcNote: "Sem expansão de campanha. O online é outro produto.",
    playModes: { offline: true, multiplayer: "Red Dead Online à parte" },
  },
  "god-of-war": {
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    ageRating: "18",
    releaseDate: "20 abr 2018",
    platforms: ["PC", "PlayStation"],
    stores: stores("steam", "playstation"),
    pcSpecs: SPEC_OPEN,
    languages: WESTERN_DUB,
    dlcs: NONE,
    playModes: { offline: true },
  },
  hades: {
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    ageRating: "16",
    releaseDate: "17 set 2020",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, ZH, KO],
    dlcs: NONE,
    dlcNote: "O jogo é o pacote. Hades II é outro cabinet.",
    playModes: { offline: true },
  },
  celeste: {
    developer: "Extremely OK Games",
    publisher: "Maddy Makes Games",
    ageRating: "10",
    releaseDate: "25 jan 2018",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, JP, ZH],
    dlcs: [
      dlc("Farewell", "Capítulo extra gratuito. A casa avisa: é o mais duro.", "steam"),
    ],
    playModes: { offline: true, note: "Assist mode incluso. Sem loja." },
  },
  "hollow-knight": {
    developer: "Team Cherry",
    publisher: "Team Cherry",
    ageRating: "10",
    releaseDate: "24 fev 2017",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "gog", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, IT_SUBS, ZH, KO, RU],
    dlcs: [
      dlc("Hidden Dreams / The Grimm Troupe / Lifeblood / Godmaster", "Conteúdo gratuito. A platina mora no Panteão.", "steam"),
    ],
    playModes: { offline: true },
  },
  "baldurs-gate-3": {
    developer: "Larian Studios",
    publisher: "Larian Studios",
    ageRating: "18",
    releaseDate: "3 ago 2023",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "gog", "playstation", "xbox"),
    pcSpecs: pc(
      sheet(WIN10, "Intel Core i5-4690 / AMD FX-8350", "GTX 970 / RX 480", "8 GB", "150 GB SSD"),
      sheet(WIN10, "Intel Core i7-8700K / Ryzen 5 3600", "RTX 2060 Super / RX 5700 XT", "16 GB", "150 GB SSD"),
    ),
    languages: [PT_SUBS, EN, ES_LATAM, FR, DE, IT_SUBS, PL, RU, ZH],
    dlcs: NONE,
    dlcNote: "Patches e o Mod Manager. Sem expansão paga ainda.",
    playModes: {
      offline: true,
      coop: "Até 4 jogadores",
      note: "Split-screen no console. Offline 100%.",
    },
  },
  "cyberpunk-2077": {
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    ageRating: "18",
    releaseDate: "10 dez 2020",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "gog", "playstation", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, PL, RU, ZH],
    dlcs: [
      dlc("Phantom Liberty", "A expansão. A casa trata como o jogo que o lançamento prometeu.", "steam", "gog"),
    ],
    playModes: { offline: true },
  },
  "disco-elysium": {
    developer: "ZA/UM",
    publisher: "ZA/UM",
    ageRating: "18",
    releaseDate: "15 out 2019",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "gog", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, RU, ZH],
    dlcs: NONE,
    dlcNote: "The Final Cut já vem no pacote — vozes e conteúdo político extra.",
    playModes: { offline: true },
  },
  "outer-wilds": {
    developer: "Mobius Digital",
    publisher: "Annapurna Interactive",
    ageRating: "10",
    releaseDate: "30 mai 2019",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, ZH],
    dlcs: [
      dlc("Echoes of the Eye", "DLC. Joga cego. A casa não discute isso na mesa.", "steam"),
    ],
    playModes: { offline: true, note: "Não google. Não abre wiki. Sério." },
  },
  "stardew-valley": {
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    ageRating: "Livre",
    releaseDate: "26 fev 2016",
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    stores: stores("steam", "gog", "playstation", "xbox", "nintendo", "mobile"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, JP, ZH, KO, RU],
    dlcs: NONE,
    dlcNote: "Updates grandes e grátis. 1.6 é o pacote atual.",
    playModes: { offline: true, coop: "Fazenda split ou online, até 4" },
  },
  minecraft: {
    developer: "Mojang Studios",
    publisher: "Microsoft",
    ageRating: "Livre",
    releaseDate: "18 nov 2011",
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    stores: stores("microsoft", "playstation", "xbox", "nintendo", "mobile"),
    pcSpecs: pc(
      sheet(WIN10, "Intel Core i3-3210 / AMD A8-7600", "Intel HD 4000 / Radeon R5", "4 GB", "4 GB"),
      sheet(WIN10, "Intel Core i5-4690 / Ryzen 5 1500X", "GTX 700 / Radeon 7000", "8 GB", "4 GB"),
      "Java na Microsoft / launcher. Bedrock é outra loja.",
    ),
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH, KO],
    dlcs: LIVE,
    dlcNote: "Marketplace é visual e mapa. O progresso vanilla não se compra.",
    playModes: { offline: true, multiplayer: "Realms / servidor" },
  },
  "persona-5-royal": {
    developer: "Atlus",
    publisher: "Sega",
    ageRating: "16",
    releaseDate: "31 out 2019",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, JP],
    dlcs: [
      dlc("Persona e trajes", "Cosmético e Persona extra. A Royal já é a versão certa.", "steam"),
    ],
    playModes: { offline: true },
  },
  "the-last-of-us-part-i": {
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    ageRating: "18",
    releaseDate: "2 set 2022",
    platforms: ["PC", "PlayStation"],
    stores: stores("steam", "playstation"),
    pcSpecs: SPEC_MODERN,
    languages: WESTERN_DUB,
    dlcs: [
      dlc("Left Behind", "Já incluso no Part I. Não é extra pago.", "steam", "playstation"),
    ],
    playModes: { offline: true },
  },
  "alan-wake-2": {
    developer: "Remedy Entertainment",
    publisher: "Epic Games Publishing",
    ageRating: "18",
    releaseDate: "27 out 2023",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("epic", "playstation", "xbox"),
    pcSpecs: SPEC_UE5,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, IT_SUBS],
    dlcs: [
      dlc("Night Springs", "Episódios curtos. Tom diferente, mesmo Lake.", "epic"),
      dlc("The Lake House", "A casa recomenda depois do jogo base.", "epic"),
    ],
    playModes: { offline: true },
  },
  "black-myth-wukong": {
    developer: "Game Science",
    publisher: "Game Science",
    ageRating: "16",
    releaseDate: "20 ago 2024",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_UE5,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, ZH, JP, KO],
    dlcs: NONE,
    playModes: { offline: true },
  },
  "expedition-33": {
    developer: "Sandfall Interactive",
    publisher: "Kepler Interactive",
    ageRating: "16",
    releaseDate: "24 abr 2025",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_UE5,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR, DE_SUBS],
    dlcs: NONE,
    playModes: { offline: true },
  },
  "helldivers-2": {
    developer: "Arrowhead Game Studios",
    publisher: "Sony Interactive Entertainment",
    ageRating: "16",
    releaseDate: "8 fev 2024",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP],
    dlcs: LIVE,
    dlcNote: "Warbonds e super credits. A democracia não se paga — o visual, às vezes.",
    playModes: {
      offline: false,
      alwaysOnline: true,
      coop: "Até 4 na mesma gota",
      note: "Precisa de rede. Host migration existe, mas instável.",
    },
  },
  "counter-strike-2": {
    developer: "Valve",
    publisher: "Valve",
    ageRating: "16",
    releaseDate: "27 set 2023",
    platforms: ["PC"],
    stores: stores("steam"),
    pcSpecs: pc(
      sheet(WIN10, "Intel Core i5-750 / Phenom II X4 965", "GTX 660 / HD 7870", "8 GB", "85 GB"),
      sheet(WIN10, "Intel Core i5-9600K / Ryzen 5 2600X", "GTX 1660 / RX 580", "8 GB", "85 GB SSD"),
    ),
    languages: LIVE_OPS,
    dlcs: LIVE,
    dlcNote: "Skins. A mira não se compra — o inventário, sim.",
    playModes: { offline: false, alwaysOnline: true, multiplayer: "5v5 competitivo" },
  },
  valorant: {
    developer: "Riot Games",
    publisher: "Riot Games",
    ageRating: "16",
    releaseDate: "2 jun 2020",
    platforms: ["PC"],
    stores: stores("launcher"),
    pcSpecs: pc(
      sheet(WIN10, "Intel Core i3-4150 / Ryzen 3 1200", "GTX 730 / Radeon R7 240", "4 GB", "20 GB"),
      sheet(WIN10, "Intel Core i5-4460 / Ryzen 5 2600X", "GTX 1050 Ti / RX 570", "8 GB", "20 GB SSD"),
      "Vanguard no boot. Sem isso, sem partida.",
    ),
    languages: LIVE_OPS,
    dlcs: LIVE,
    dlcNote: "Battle pass e skin. Agente se destrava jogando.",
    playModes: { offline: false, alwaysOnline: true, multiplayer: "5v5 tático" },
  },
  "apex-legends": {
    developer: "Respawn Entertainment",
    publisher: "Electronic Arts",
    ageRating: "16",
    releaseDate: "4 fev 2019",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_OPEN,
    languages: LIVE_OPS,
    dlcs: LIVE,
    dlcNote: "Evento e heirloom. A skill não se compra — o visual, toda season.",
    playModes: { offline: false, alwaysOnline: true, multiplayer: "BR 3 squad" },
  },
  "overwatch-2": {
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    ageRating: "12",
    releaseDate: "4 out 2022",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("launcher", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH, KO],
    dlcs: LIVE,
    playModes: { offline: false, alwaysOnline: true, multiplayer: "5v5" },
  },
  "destiny-2": {
    developer: "Bungie",
    publisher: "Bungie",
    ageRating: "16",
    releaseDate: "6 set 2017",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, IT_SUBS, JP, RU],
    dlcs: LIVE,
    dlcNote: "A campanha some do vault. Expansão atual é o que a casa joga.",
    playModes: { offline: false, alwaysOnline: true, coop: "Strike / raid" },
  },
  "diablo-iv": {
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    ageRating: "18",
    releaseDate: "5 jun 2023",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("launcher", "playstation", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH, KO],
    dlcs: [
      dlc("Vessel of Hatred", "Expansão. Season continua no calendário live.", "launcher"),
    ],
    playModes: { offline: false, alwaysOnline: true, coop: "Open world" },
  },
  "path-of-exile": {
    developer: "Grinding Gear Games",
    publisher: "Grinding Gear Games",
    ageRating: "16",
    releaseDate: "23 out 2013",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "official", "playstation", "xbox"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_UI, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, RU, ZH],
    dlcs: LIVE,
    dlcNote: "Supporter pack. O poder no P2W da liga é o que a casa discute.",
    playModes: { offline: false, alwaysOnline: true },
  },
  "league-of-legends": {
    developer: "Riot Games",
    publisher: "Riot Games",
    ageRating: "12",
    releaseDate: "27 out 2009",
    platforms: ["PC"],
    stores: stores("launcher"),
    pcSpecs: pc(
      sheet(WIN10, "Intel Core i3-530 / AMD A6-3650", "Intel HD 4000", "4 GB", "16 GB"),
      sheet(WIN10, "Intel Core i5-3300 / Ryzen 3 1200", "GTX 560 / HD 7750", "8 GB", "16 GB"),
    ),
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH, KO],
    dlcs: LIVE,
    dlcNote: "Skin e passe. Champion se destrava grátis — lento, mas dá.",
    playModes: { offline: false, alwaysOnline: true, multiplayer: "5v5" },
  },
  "dota-2": {
    developer: "Valve",
    publisher: "Valve",
    ageRating: "12",
    releaseDate: "9 jul 2013",
    platforms: ["PC"],
    stores: stores("steam"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, RU, ZH],
    dlcs: LIVE,
    playModes: { offline: false, alwaysOnline: true, multiplayer: "5v5" },
  },
  hearthstone: {
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    ageRating: "Livre",
    releaseDate: "11 mar 2014",
    platforms: ["PC", "Mobile"],
    stores: stores("launcher", "mobile"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH, KO],
    dlcs: LIVE,
    dlcNote: "Pacote e passe. O poder mora no caixa da temporada.",
    playModes: { offline: false, alwaysOnline: true },
  },
  "genshin-impact": {
    developer: "HoYoverse",
    publisher: "HoYoverse",
    ageRating: "12",
    releaseDate: "28 set 2020",
    platforms: ["PC", "PlayStation", "Mobile"],
    stores: stores("launcher", "playstation", "mobile"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, JP, ZH, KO],
    dlcs: LIVE,
    dlcNote: "Banner e pity. Dá pra ir F2P — o maxo cobra o C6.",
    playModes: { offline: false, alwaysOnline: true, coop: "Mundo até 4" },
  },
  "honkai-star-rail": {
    developer: "HoYoverse",
    publisher: "HoYoverse",
    ageRating: "12",
    releaseDate: "26 abr 2023",
    platforms: ["PC", "PlayStation", "Mobile"],
    stores: stores("launcher", "playstation", "mobile"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, JP, ZH, KO],
    dlcs: LIVE,
    playModes: { offline: false, alwaysOnline: true },
  },
  fortnite: {
    developer: "Epic Games",
    publisher: "Epic Games",
    ageRating: "12",
    releaseDate: "25 jul 2017",
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    stores: stores("epic", "playstation", "xbox", "nintendo", "mobile"),
    pcSpecs: SPEC_OPEN,
    languages: LIVE_OPS,
    dlcs: LIVE,
    playModes: { offline: false, alwaysOnline: true, multiplayer: "BR / Zero Build" },
  },
  "pubg-battlegrounds": {
    developer: "KRAFTON",
    publisher: "KRAFTON",
    ageRating: "16",
    releaseDate: "23 mar 2017",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, ZH, KO, JP, RU],
    dlcs: LIVE,
    playModes: { offline: false, alwaysOnline: true, multiplayer: "BR" },
  },
  "marvel-rivals": {
    developer: "NetEase Games",
    publisher: "NetEase Games",
    ageRating: "12",
    releaseDate: "6 dez 2024",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, ZH, JP, KO],
    dlcs: LIVE,
    playModes: { offline: false, alwaysOnline: true, multiplayer: "6v6 hero shooter" },
  },
  palworld: {
    developer: "Pocketpair",
    publisher: "Pocketpair",
    ageRating: "12",
    releaseDate: "19 jan 2024",
    platforms: ["PC", "Xbox"],
    stores: stores("steam", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, JP, ZH, KO],
    dlcs: LIVE,
    dlcNote: "Early access. Passe de pal e skin. O bicho se pega no mapa.",
    playModes: { offline: true, coop: "Servidor dedicado / friends" },
  },
  "no-mans-sky": {
    developer: "Hello Games",
    publisher: "Hello Games",
    ageRating: "10",
    releaseDate: "9 ago 2016",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_OPEN,
    languages: WESTERN,
    dlcs: NONE,
    dlcNote: "Toda atualização grande é grátis. A casa respeita.",
    playModes: { offline: true, coop: "Nexus / friends" },
  },
  "sea-of-thieves": {
    developer: "Rare",
    publisher: "Xbox Game Studios",
    ageRating: "12",
    releaseDate: "20 mar 2018",
    platforms: ["PC", "Xbox"],
    stores: stores("steam", "microsoft", "xbox"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE],
    dlcs: LIVE,
    dlcNote: "Emporium de visual. O tesouro se farmá no mar.",
    playModes: { offline: false, alwaysOnline: true, coop: "Sloop / brig / galleon" },
  },
  "deep-rock-galactic": {
    developer: "Ghost Ship Games",
    publisher: "Coffee Stain Publishing",
    ageRating: "16",
    releaseDate: "13 mai 2020",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, ZH, RU],
    dlcs: [
      dlc("Cosmetic packs", "Barba, pickaxe, a dança. Rock and stone não se compra.", "steam"),
    ],
    playModes: { offline: true, coop: "Até 4 anões" },
  },
  "zelda-breath-of-the-wild": {
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    ageRating: "10",
    releaseDate: "3 mar 2017",
    platforms: ["Switch", "Wii U"],
    stores: stores("nintendo"),
    pcSpecs: "not-pc",
    pcNote: "Exclusivo Nintendo. A ficha de máquina de PC não entra.",
    languages: [PT_SUBS, EN, ES_ES, FR_SUBS, DE_SUBS, IT_SUBS, JP],
    dlcs: [
      dlc("The Master Trials", "Prova e master mode. A casa discute se vale o pack.", "nintendo"),
      dlc("The Champion's Ballad", "A segunda metade do pack. Mapa extra, trial extra.", "nintendo"),
    ],
    playModes: { offline: true },
  },
  "zelda-tears-of-the-kingdom": {
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    ageRating: "10",
    releaseDate: "12 mai 2023",
    platforms: ["Switch"],
    stores: stores("nintendo"),
    pcSpecs: "not-pc",
    pcNote: "Exclusivo Switch. Sem versão de PC.",
    languages: [PT_SUBS, EN, ES_ES, FR_SUBS, DE_SUBS, IT_SUBS, JP],
    dlcs: NONE,
    playModes: { offline: true },
  },
  "super-mario-odyssey": {
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    ageRating: "Livre",
    releaseDate: "27 out 2017",
    platforms: ["Switch"],
    stores: stores("nintendo"),
    pcSpecs: "not-pc",
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP],
    dlcs: NONE,
    playModes: { offline: true, coop: "2P no chapéu" },
  },
  "animal-crossing-new-horizons": {
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    ageRating: "Livre",
    releaseDate: "20 mar 2020",
    platforms: ["Switch"],
    stores: stores("nintendo"),
    pcSpecs: "not-pc",
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH, KO],
    dlcs: [
      dlc("Happy Home Paradise", "A ilha de encomenda. A casa trata como extra, não obrigatório.", "nintendo"),
    ],
    playModes: { offline: true, coop: "Visita / Dodo" },
  },
  "pokemon-scarlet-violet": {
    developer: "Game Freak",
    publisher: "Nintendo / The Pokémon Company",
    ageRating: "Livre",
    releaseDate: "18 nov 2022",
    platforms: ["Switch"],
    stores: stores("nintendo"),
    pcSpecs: "not-pc",
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, IT_SUBS, JP, ZH, KO],
    dlcs: [
      dlc("The Hidden Treasure of Area Zero", "The Teal Mask + The Indigo Disk. A casa discute se o online segura.", "nintendo"),
    ],
    playModes: { offline: true, coop: "Mundo aberto online" },
  },
  "super-smash-bros-ultimate": {
    developer: "Bandai Namco / Sora Ltd.",
    publisher: "Nintendo",
    ageRating: "10",
    releaseDate: "7 dez 2018",
    platforms: ["Switch"],
    stores: stores("nintendo"),
    pcSpecs: "not-pc",
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP],
    dlcs: [
      dlc("Fighters Pass Vol. 1 e 2", "Personagem extra. O roster base já é absurdo.", "nintendo"),
    ],
    playModes: { offline: true, multiplayer: "Local e online" },
  },
  "portal-2": {
    developer: "Valve",
    publisher: "Valve",
    ageRating: "10",
    releaseDate: "19 abr 2011",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, RU, ZH],
    dlcs: NONE,
    playModes: { offline: true, coop: "Campanha 2P — a casa insiste" },
  },
  "half-life-2": {
    developer: "Valve",
    publisher: "Valve",
    ageRating: "16",
    releaseDate: "16 nov 2004",
    platforms: ["PC"],
    stores: stores("steam"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, RU],
    dlcs: [
      dlc("Episode One / Episode Two", "A continuação. Ainda sem o 3.", "steam"),
    ],
    playModes: { offline: true },
  },
  "resident-evil-4-remake": {
    developer: "Capcom",
    publisher: "Capcom",
    ageRating: "18",
    releaseDate: "24 mar 2023",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH],
    dlcs: [
      dlc("Separate Ways", "Ada. A casa trata como o bis obrigatório.", "steam"),
      dlc("The Mercenaries", "Já no disco. Score attack.", "steam"),
    ],
    playModes: { offline: true },
  },
  "doom-eternal": {
    developer: "id Software",
    publisher: "Bethesda Softworks",
    ageRating: "18",
    releaseDate: "20 mar 2020",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, IT_SUBS, JP, RU],
    dlcs: [
      dlc("The Ancient Gods — Part One", "A primeira metade do DLC. Mais UN, mais inferno.", "steam"),
      dlc("The Ancient Gods — Part Two", "Fecha o pacote. A casa discute se passa o base.", "steam"),
    ],
    playModes: { offline: true, multiplayer: "Battlemode à parte" },
  },
  returnal: {
    developer: "Housemarque",
    publisher: "Sony Interactive Entertainment",
    ageRating: "16",
    releaseDate: "30 abr 2021",
    platforms: ["PC", "PlayStation"],
    stores: stores("steam", "playstation"),
    pcSpecs: SPEC_MODERN,
    languages: WESTERN_DUB,
    dlcs: [
      dlc("Tower of Sisyphus", "Já incluso. Roguelike vertical no mesmo save.", "steam", "playstation"),
    ],
    playModes: { offline: true, coop: "Returnal+ Ascension, 2P" },
  },
  "it-takes-two": {
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    ageRating: "12",
    releaseDate: "26 mar 2021",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, IT_SUBS],
    dlcs: NONE,
    playModes: {
      offline: true,
      coop: "Obrigatório — 2P local ou online",
      note: "Friend’s Pass: um compra, o outro entra.",
    },
  },
  "street-fighter-6": {
    developer: "Capcom",
    publisher: "Capcom",
    ageRating: "12",
    releaseDate: "2 jun 2023",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH, KO],
    dlcs: LIVE,
    dlcNote: "Year pass de personagem. O ranked é skill — o roster, temporada.",
    playModes: { offline: true, multiplayer: "Fighting ground / ranked" },
  },
  "tekken-8": {
    developer: "Bandai Namco",
    publisher: "Bandai Namco",
    ageRating: "16",
    releaseDate: "26 jan 2024",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_UE5,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, JP, ZH, KO],
    dlcs: LIVE,
    playModes: { offline: true, multiplayer: "Ranked / player match" },
  },
  "rocket-league": {
    developer: "Psyonix",
    publisher: "Epic Games",
    ageRating: "Livre",
    releaseDate: "7 jul 2015",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("epic", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE],
    dlcs: LIVE,
    dlcNote: "Fortnite-style shop. A bola não se compra.",
    playModes: { offline: true, multiplayer: "3v3 ranked" },
  },
  "forza-horizon-5": {
    developer: "Playground Games",
    publisher: "Xbox Game Studios",
    ageRating: "Livre",
    releaseDate: "9 nov 2021",
    platforms: ["PC", "Xbox"],
    stores: stores("steam", "microsoft", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE],
    dlcs: [
      dlc("Hot Wheels", "Pista vertical. A casa ama.", "steam", "xbox"),
      dlc("Rally Adventure", "Terra e co-driver. Fecha o pacote.", "steam", "xbox"),
    ],
    playModes: { offline: true, multiplayer: "Festival aberto" },
  },
  "gran-turismo-7": {
    developer: "Polyphony Digital",
    publisher: "Sony Interactive Entertainment",
    ageRating: "Livre",
    releaseDate: "4 mar 2022",
    platforms: ["PlayStation"],
    stores: stores("playstation"),
    pcSpecs: "not-pc",
    pcNote: "Exclusivo PlayStation. Sem versão de PC neste catálogo.",
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP],
    dlcs: LIVE,
    dlcNote: "Carro e crédito. A casa resmunga do grind — o handling é o jogo.",
    playModes: { offline: true, alwaysOnline: true, multiplayer: "Sport mode" },
  },
  starfield: {
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    ageRating: "16",
    releaseDate: "6 set 2023",
    platforms: ["PC", "Xbox"],
    stores: stores("steam", "microsoft", "xbox"),
    pcSpecs: SPEC_UE5,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH],
    dlcs: [
      dlc("Shattered Space", "A expansão. A casa ainda discute se o base vale.", "steam"),
    ],
    playModes: { offline: true },
  },
  "lies-of-p": {
    developer: "Round8 Studio",
    publisher: "Neowiz",
    ageRating: "16",
    releaseDate: "18 set 2023",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_SOULS,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, JP, ZH, KO],
    dlcs: [
      dlc("Overture", "Prequel. Armas novas, chefes novos. A casa recomenda depois do base.", "steam"),
    ],
    playModes: { offline: true },
  },
  "sekiro-shadows-die-twice": {
    developer: "FromSoftware",
    publisher: "Activision",
    ageRating: "18",
    releaseDate: "22 mar 2019",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_SOULS,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, JP],
    dlcs: NONE,
    playModes: { offline: true },
  },
  "dark-souls-3": {
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    ageRating: "16",
    releaseDate: "24 mar 2016",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_SOULS,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, JP],
    dlcs: [
      dlc("Ashes of Ariandel", "A primeira metade. A casa avisa: o 2 é o auge.", "steam"),
      dlc("The Ringed City", "Fecha. Gael. Sem spoiler no resto.", "steam"),
    ],
    playModes: { offline: true, coop: "Sino opcional", multiplayer: "Invasão" },
  },
  bloodborne: {
    developer: "FromSoftware",
    publisher: "Sony Interactive Entertainment",
    ageRating: "18",
    releaseDate: "24 mar 2015",
    platforms: ["PlayStation"],
    stores: stores("playstation"),
    pcSpecs: "not-pc",
    pcNote: "Nasceu no PlayStation. Sem versão de PC neste catálogo — a casa ainda espera.",
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, JP],
    dlcs: [
      dlc("The Old Hunters", "A casa trata como obrigatório se você achar.", "playstation"),
    ],
    playModes: { offline: true, coop: "Sino opcional" },
  },
  "ghost-of-tsushima": {
    developer: "Sucker Punch",
    publisher: "Sony Interactive Entertainment",
    ageRating: "18",
    releaseDate: "17 jul 2020",
    platforms: ["PC", "PlayStation"],
    stores: stores("steam", "playstation"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, JP],
    dlcs: [
      dlc("Iki Island", "Já na Director's Cut. A casa recomenda o pacote completo.", "steam", "playstation"),
    ],
    playModes: { offline: true, multiplayer: "Legends à parte" },
  },
  "spider-man-remastered": {
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    ageRating: "16",
    releaseDate: "12 ago 2022",
    platforms: ["PC", "PlayStation"],
    stores: stores("steam", "playstation"),
    pcSpecs: SPEC_MODERN,
    languages: WESTERN_DUB,
    dlcs: [
      dlc("The City That Never Sleeps", "Três episódios. Já no Remastered.", "steam"),
    ],
    playModes: { offline: true },
  },
  "final-fantasy-vii-remake": {
    developer: "Square Enix",
    publisher: "Square Enix",
    ageRating: "16",
    releaseDate: "10 abr 2020",
    platforms: ["PC", "PlayStation"],
    stores: stores("steam", "playstation"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_SUBS, EN, ES_LATAM, JP],
    dlcs: [
      dlc("INTERmission", "Yuffie. Já no Intergrade.", "steam", "playstation"),
    ],
    playModes: { offline: true },
  },
  "mass-effect-legendary": {
    developer: "BioWare",
    publisher: "Electronic Arts",
    ageRating: "18",
    releaseDate: "14 mai 2021",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE],
    dlcs: NONE,
    dlcNote: "A Legendary já vem com os DLCs clássicos. É o pacote certo.",
    playModes: { offline: true },
  },
  "indiana-jones-great-circle": {
    developer: "MachineGames",
    publisher: "Bethesda Softworks",
    ageRating: "16",
    releaseDate: "9 dez 2024",
    platforms: ["PC", "Xbox", "PlayStation"],
    stores: stores("steam", "microsoft", "xbox", "playstation"),
    pcSpecs: SPEC_UE5,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE],
    dlcs: [
      dlc("The Order of Giants", "A expansão. A casa ainda está no base.", "steam"),
    ],
    playModes: { offline: true },
  },
  "payday-2": {
    developer: "OVERKILL",
    publisher: "Starbreeze Studios",
    ageRating: "18",
    releaseDate: "13 ago 2013",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, RU],
    dlcs: LIVE,
    dlcNote: "DLC demais. O poder pago aparece — a casa resmunga.",
    playModes: { offline: true, coop: "Heist até 4" },
  },
  "left-4-dead-2": {
    developer: "Valve",
    publisher: "Valve",
    ageRating: "18",
    releaseDate: "17 nov 2009",
    platforms: ["PC"],
    stores: stores("steam"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, RU],
    dlcs: NONE,
    dlcNote: "Campanhas extras vieram grátis. Workshop é o resto.",
    playModes: { offline: true, coop: "Campanha 4 / versus" },
  },
  balatro: {
    developer: "LocalThunk",
    publisher: "Playstack",
    ageRating: "Livre",
    releaseDate: "20 fev 2024",
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    stores: stores("steam", "playstation", "xbox", "nintendo", "mobile"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, ZH, JP],
    dlcs: NONE,
    playModes: { offline: true },
  },
  "slay-the-spire": {
    developer: "MegaCrit",
    publisher: "MegaCrit",
    ageRating: "10",
    releaseDate: "23 jan 2019",
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    stores: stores("steam", "playstation", "xbox", "nintendo", "mobile"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, ZH, JP, KO],
    dlcs: NONE,
    playModes: { offline: true },
  },
  "vampire-survivors": {
    developer: "poncle",
    publisher: "poncle",
    ageRating: "12",
    releaseDate: "20 out 2022",
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    stores: stores("steam", "playstation", "xbox", "nintendo", "mobile"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, IT_SUBS, ZH, JP],
    dlcs: [
      dlc("Legacy of the Moonspell / Tides of the Foscari / Ode to Castlevania", "Packs de palco e personagem. Baratinho. Conteúdo, não poder pago no PvP — não tem PvP.", "steam"),
    ],
    playModes: { offline: true, coop: "Local" },
  },
  "dead-cells": {
    developer: "Motion Twin",
    publisher: "Motion Twin",
    ageRating: "16",
    releaseDate: "6 ago 2018",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "gog", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, ZH, JP],
    dlcs: [
      dlc("Rise of the Giant / The Bad Seed / Fatal Falls / The Queen and the Sea / Return to Castlevania", "A soma é o jogo completo. Cada um é conteúdo, não lootbox.", "steam"),
    ],
    playModes: { offline: true },
  },
  undertale: {
    developer: "tobyfox",
    publisher: "tobyfox",
    ageRating: "10",
    releaseDate: "15 set 2015",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, JP],
    dlcs: NONE,
    playModes: { offline: true, note: "Não spoila. A casa pede isso de verdade." },
  },
  control: {
    developer: "Remedy Entertainment",
    publisher: "505 Games",
    ageRating: "16",
    releaseDate: "27 ago 2019",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "epic", "playstation", "xbox"),
    pcSpecs: SPEC_OPEN,
    languages: WESTERN,
    dlcs: [
      dlc("The Foundation", "A casa recomenda. O Oldest House desce.", "steam"),
      dlc("AWE", "Cruza com Alan Wake. Fecha o pacote Ultimate.", "steam"),
    ],
    playModes: { offline: true },
  },
  "horizon-zero-dawn": {
    developer: "Guerrilla Games",
    publisher: "Sony Interactive Entertainment",
    ageRating: "16",
    releaseDate: "28 fev 2017",
    platforms: ["PC", "PlayStation"],
    stores: stores("steam", "playstation"),
    pcSpecs: SPEC_OPEN,
    languages: WESTERN_DUB,
    dlcs: [
      dlc("The Frozen Wilds", "A Complete Edition já vem. A casa trata como o bis certo.", "steam"),
    ],
    playModes: { offline: true },
  },
  "monster-hunter-world": {
    developer: "Capcom",
    publisher: "Capcom",
    ageRating: "16",
    releaseDate: "26 jan 2018",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_OPEN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP, ZH, KO],
    dlcs: [
      dlc("Iceborne", "O endgame. A casa não recomenda o base sozinho no 2026.", "steam"),
    ],
    playModes: { offline: true, coop: "Caçada até 4" },
  },
  "armored-core-vi": {
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    ageRating: "16",
    releaseDate: "25 ago 2023",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_SOULS,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, JP, ZH, KO],
    dlcs: NONE,
    playModes: { offline: true, multiplayer: "PvP opcional" },
  },
  "kingdom-come-deliverance-2": {
    developer: "Warhorse Studios",
    publisher: "Deep Silver",
    ageRating: "18",
    releaseDate: "4 fev 2025",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_UE5,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, DE, PL],
    dlcs: NONE,
    playModes: { offline: true },
  },
  enshrouded: {
    developer: "Keen Games",
    publisher: "Keen Games",
    ageRating: "16",
    releaseDate: "24 jan 2024",
    platforms: ["PC"],
    stores: stores("steam"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, DE_SUBS, ZH],
    dlcs: NONE,
    dlcNote: "Early access. Updates no roadmap, sem loja de poder.",
    playModes: { offline: true, coop: "Até 16 no dedicated" },
  },
  "astro-bot": {
    developer: "Team Asobi",
    publisher: "Sony Interactive Entertainment",
    ageRating: "Livre",
    releaseDate: "6 set 2024",
    platforms: ["PlayStation"],
    stores: stores("playstation"),
    pcSpecs: "not-pc",
    pcNote: "Exclusivo PlayStation. DualSense é o game.",
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, JP],
    dlcs: NONE,
    playModes: { offline: true },
  },
  "ratchet-clank-rift-apart": {
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    ageRating: "10",
    releaseDate: "11 jun 2021",
    platforms: ["PC", "PlayStation"],
    stores: stores("steam", "playstation"),
    pcSpecs: SPEC_MODERN,
    languages: WESTERN_DUB,
    dlcs: NONE,
    playModes: { offline: true },
  },
  "f1-24": {
    developer: "Codemasters",
    publisher: "EA Sports",
    ageRating: "Livre",
    releaseDate: "31 mai 2024",
    platforms: ["PC", "PlayStation", "Xbox"],
    stores: stores("steam", "playstation", "xbox"),
    pcSpecs: SPEC_MODERN,
    languages: [PT_FULL, EN, ES_LATAM, FR, DE, IT_SUBS, JP],
    dlcs: LIVE,
    playModes: { offline: true, multiplayer: "Liga / ranked" },
  },
  "hollow-knight-silksong": {
    developer: "Team Cherry",
    publisher: "Team Cherry",
    ageRating: "10",
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    stores: stores("steam", "playstation", "xbox", "nintendo"),
    pcSpecs: SPEC_INDIE,
    languages: [PT_SUBS, EN, ES_LATAM_SUBS, FR_SUBS, DE_SUBS, ZH],
    dlcs: NONE,
    playModes: { offline: true },
  },
};
