export type SeedGame = {
  slug: string;
  title: string;
  synopsis: string;
  steamAppId: number;
  releaseYear: number;
  genres: string[];
  platforms: string[];
  metacritic?: number;
  coverUrl: string;
};

function steamCover(appId: number) {
  return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`;
}

export const seedGames: SeedGame[] = [
  {
    slug: "the-witcher-3-wild-hunt",
    title: "The Witcher 3: Wild Hunt",
    synopsis:
      "Geralt de Rivia caça a Criança da Profecia em um mundo aberto repleto de monstros, política e escolhas difíceis.",
    steamAppId: 292030,
    releaseYear: 2015,
    genres: ["RPG", "Ação", "Aventura"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 93,
  },
  {
    slug: "elden-ring",
    title: "Elden Ring",
    synopsis:
      "Um RPG de ação épico em mundo aberto criado por FromSoftware e George R. R. Martin.",
    steamAppId: 1245620,
    releaseYear: 2022,
    genres: ["RPG", "Ação", "Soulslike"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 96,
  },
  {
    slug: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    synopsis:
      "A história de Arthur Morgan e a gangue Van der Linde no declínio do Velho Oeste americano.",
    steamAppId: 1174180,
    releaseYear: 2018,
    genres: ["Ação", "Aventura", "Western"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 97,
  },
  {
    slug: "god-of-war",
    title: "God of War",
    synopsis:
      "Kratos e Atreus atravessam a mitologia nórdica em uma jornada emocional de pai e filho.",
    steamAppId: 1593500,
    releaseYear: 2018,
    genres: ["Ação", "Aventura", "Hack and Slash"],
    platforms: ["PC", "PlayStation"],
    metacritic: 94,
  },
  {
    slug: "hades",
    title: "Hades",
    synopsis:
      "Roguelike de ação onde Zagreus tenta escapar do submundo grego a cada run.",
    steamAppId: 1145360,
    releaseYear: 2020,
    genres: ["Roguelike", "Ação", "Indie"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 93,
  },
  {
    slug: "celeste",
    title: "Celeste",
    synopsis:
      "Plataforma desafiadora sobre escalar o Monte Celeste e superar ansiedade.",
    steamAppId: 504230,
    releaseYear: 2018,
    genres: ["Plataforma", "Indie", "Precisão"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 92,
  },
  {
    slug: "hollow-knight",
    title: "Hollow Knight",
    synopsis:
      "Metroidvania sombrio em Hallownest, cheio de segredos e combate preciso.",
    steamAppId: 367520,
    releaseYear: 2017,
    genres: ["Metroidvania", "Ação", "Indie"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 90,
  },
  {
    slug: "portal-2",
    title: "Portal 2",
    synopsis:
      "Quebra-cabeças com portal gun e humor seco em instalações da Aperture Science.",
    steamAppId: 620,
    releaseYear: 2011,
    genres: ["Puzzle", "Plataforma", "Aventura"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 95,
  },
  {
    slug: "half-life-2",
    title: "Half-Life 2",
    synopsis:
      "Gordon Freeman lidera a resistência contra o domínio alienígena da Combine.",
    steamAppId: 220,
    releaseYear: 2004,
    genres: ["FPS", "Ação", "Sci-Fi"],
    platforms: ["PC", "Xbox"],
    metacritic: 96,
  },
  {
    slug: "bioshock-infinite",
    title: "BioShock Infinite",
    synopsis:
      "Booker DeWitt busca Elizabeth na cidade flutuante de Columbia.",
    steamAppId: 8870,
    releaseYear: 2013,
    genres: ["FPS", "Ação", "Narrativa"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 94,
  },
  {
    slug: "dark-souls-3",
    title: "Dark Souls III",
    synopsis:
      "O fim da era das chamas em um RPG de ação brutal e atmosférico.",
    steamAppId: 374320,
    releaseYear: 2016,
    genres: ["RPG", "Ação", "Soulslike"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 89,
  },
  {
    slug: "sekiro-shadows-die-twice",
    title: "Sekiro: Shadows Die Twice",
    synopsis:
      "Combate com parry e mobilidade vertical no Japão feudal fantástico.",
    steamAppId: 814380,
    releaseYear: 2019,
    genres: ["Ação", "Soulslike", "Aventura"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 90,
  },
  {
    slug: "bloodborne",
    title: "Bloodborne",
    synopsis:
      "Caçador enfrenta horrores góticos em Yharnam — clássico PlayStation.",
    steamAppId: 377160,
    releaseYear: 2015,
    genres: ["Ação", "Soulslike", "Horror"],
    platforms: ["PlayStation", "PC"],
    metacritic: 92,
  },
  {
    slug: "ghost-of-tsushima",
    title: "Ghost of Tsushima",
    synopsis:
      "Jin Sakai defende Tsushima contra a invasão mongol com honra ou furtividade.",
    steamAppId: 2215430,
    releaseYear: 2020,
    genres: ["Ação", "Aventura", "Open World"],
    platforms: ["PC", "PlayStation"],
    metacritic: 83,
  },
  {
    slug: "horizon-zero-dawn",
    title: "Horizon Zero Dawn",
    synopsis:
      "Aloy caça máquinas em um mundo pós-apocalíptico dominado por robôs.",
    steamAppId: 1151640,
    releaseYear: 2017,
    genres: ["Ação", "RPG", "Open World"],
    platforms: ["PC", "PlayStation"],
    metacritic: 89,
  },
  {
    slug: "spider-man-remastered",
    title: "Marvel's Spider-Man Remastered",
    synopsis:
      "Peter Parker protege Nova York com combate acrobático e história cinematográfica.",
    steamAppId: 1817070,
    releaseYear: 2018,
    genres: ["Ação", "Aventura", "Super-herói"],
    platforms: ["PC", "PlayStation"],
    metacritic: 87,
  },
  {
    slug: "final-fantasy-vii-remake",
    title: "FINAL FANTASY VII REMAKE",
    synopsis:
      "Cloud e Avalanche lutam contra a Shinra em Midgar reimaginada.",
    steamAppId: 1462040,
    releaseYear: 2020,
    genres: ["RPG", "Ação", "JRPG"],
    platforms: ["PC", "PlayStation"],
    metacritic: 87,
  },
  {
    slug: "persona-5-royal",
    title: "Persona 5 Royal",
    synopsis:
      "Phantom Thieves equilibram vida escolar e heists sobrenaturais em Tóquio.",
    steamAppId: 1687950,
    releaseYear: 2019,
    genres: ["RPG", "JRPG", "Turn-based"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 95,
  },
  {
    slug: "disco-elysium",
    title: "Disco Elysium",
    synopsis:
      "RPG narrativo onde suas habilidades mentais debatem cada decisão.",
    steamAppId: 632470,
    releaseYear: 2019,
    genres: ["RPG", "Narrativa", "Investigação"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 91,
  },
  {
    slug: "outer-wilds",
    title: "Outer Wilds",
    synopsis:
      "Exploração em loop temporal de 22 minutos em um sistema solar misterioso.",
    steamAppId: 753640,
    releaseYear: 2019,
    genres: ["Aventura", "Exploração", "Puzzle"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 85,
  },
  {
    slug: "stardew-valley",
    title: "Stardew Valley",
    synopsis:
      "Herde uma fazenda, cultive, pesque e construa laços em Pelican Town.",
    steamAppId: 413150,
    releaseYear: 2016,
    genres: ["Simulação", "Fazenda", "Indie"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    metacritic: 89,
  },
  {
    slug: "minecraft",
    title: "Minecraft",
    synopsis:
      "Construa, explore e sobreviva em blocos infinitos de criatividade.",
    steamAppId: 322170,
    releaseYear: 2011,
    genres: ["Sandbox", "Sobrevivência", "Criativo"],
    platforms: ["PC", "Console", "Mobile"],
    metacritic: 93,
  },
  {
    slug: "terraria",
    title: "Terraria",
    synopsis:
      "Sandbox 2D com crafting, bosses e exploração sem fim.",
    steamAppId: 105600,
    releaseYear: 2011,
    genres: ["Sandbox", "Ação", "Aventura"],
    platforms: ["PC", "Console", "Mobile"],
    metacritic: 83,
  },
  {
    slug: "factorio",
    title: "Factorio",
    synopsis:
      "Construa fábricas automatizadas em um planeta alienígena hostil.",
    steamAppId: 427520,
    releaseYear: 2020,
    genres: ["Simulação", "Estratégia", "Automação"],
    platforms: ["PC", "Switch"],
    metacritic: 90,
  },
  {
    slug: "rimworld",
    title: "RimWorld",
    synopsis:
      "Colônia sci-fi com histórias emergentes e drama procedural.",
    steamAppId: 294100,
    releaseYear: 2018,
    genres: ["Simulação", "Estratégia", "Colônia"],
    platforms: ["PC", "Console"],
    metacritic: 87,
  },
  {
    slug: "civilization-vi",
    title: "Sid Meier's Civilization VI",
    synopsis:
      "Construa um império da idade da pedra à era espacial turno a turno.",
    steamAppId: 289070,
    releaseYear: 2016,
    genres: ["Estratégia", "4X", "Turn-based"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 88,
  },
  {
    slug: "xcom-2",
    title: "XCOM 2",
    synopsis:
      "Comande a resistência contra ocupação alienígena em combate tático.",
    steamAppId: 268500,
    releaseYear: 2016,
    genres: ["Estratégia", "Tático", "Sci-Fi"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 88,
  },
  {
    slug: "total-war-warhammer-3",
    title: "Total War: WARHAMMER III",
    synopsis:
      "Batalhas épicas e campanhas no universo Warhammer Fantasy.",
    steamAppId: 1142710,
    releaseYear: 2022,
    genres: ["Estratégia", "RTS", "Fantasia"],
    platforms: ["PC"],
    metacritic: 86,
  },
  {
    slug: "counter-strike-2",
    title: "Counter-Strike 2",
    synopsis:
      "FPS tático 5v5 competitivo — o sucessor de CS:GO na Source 2.",
    steamAppId: 730,
    releaseYear: 2023,
    genres: ["FPS", "Competitivo", "Tático"],
    platforms: ["PC"],
    metacritic: 83,
  },
  {
    slug: "valorant",
    title: "VALORANT",
    synopsis:
      "FPS tático 5v5 com agentes e habilidades únicas da Riot Games.",
    steamAppId: 1274570,
    releaseYear: 2020,
    genres: ["FPS", "Competitivo", "Tático"],
    platforms: ["PC", "Console"],
    metacritic: 80,
  },
  {
    slug: "apex-legends",
    title: "Apex Legends",
    synopsis:
      "Battle royale hero shooter com movimentação fluida e squads.",
    steamAppId: 1172470,
    releaseYear: 2019,
    genres: ["Battle Royale", "FPS", "Hero Shooter"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 88,
  },
  {
    slug: "overwatch-2",
    title: "Overwatch 2",
    synopsis:
      "Hero shooter em equipe com personagens icônicos e partidas 5v5.",
    steamAppId: 2357570,
    releaseYear: 2022,
    genres: ["Hero Shooter", "FPS", "Competitivo"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 79,
  },
  {
    slug: "destiny-2",
    title: "Destiny 2",
    synopsis:
      "Looter shooter sci-fi com raids, PvP e expansões constantes.",
    steamAppId: 1085660,
    releaseYear: 2017,
    genres: ["FPS", "Looter", "MMO"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 85,
  },
  {
    slug: "diablo-iv",
    title: "Diablo IV",
    synopsis:
      "Ação RPG sombrio em Sanctuary com loot, dungeons e seasons.",
    steamAppId: 2344520,
    releaseYear: 2023,
    genres: ["ARPG", "Ação", "Hack and Slash"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 86,
  },
  {
    slug: "path-of-exile",
    title: "Path of Exile",
    synopsis:
      "ARPG free-to-play com árvore de passivas profunda e leagues.",
    steamAppId: 238960,
    releaseYear: 2013,
    genres: ["ARPG", "Ação", "Free-to-play"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 86,
  },
  {
    slug: "monster-hunter-world",
    title: "Monster Hunter: World",
    synopsis:
      "Caçe monstros colossais solo ou em coop de até 4 jogadores.",
    steamAppId: 582010,
    releaseYear: 2018,
    genres: ["Ação", "RPG", "Co-op"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 90,
  },
  {
    slug: "monster-hunter-rise",
    title: "Monster Hunter Rise",
    synopsis:
      "Caçadas verticais com Wirebugs e palicos em Kamura Village.",
    steamAppId: 1446780,
    releaseYear: 2021,
    genres: ["Ação", "RPG", "Co-op"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 88,
  },
  {
    slug: "devil-may-cry-5",
    title: "Devil May Cry 5",
    synopsis:
      "Hack and slash estiloso com Nero, Dante e V contra demônios.",
    steamAppId: 601150,
    releaseYear: 2019,
    genres: ["Ação", "Hack and Slash", "Stylish"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 88,
  },
  {
    slug: "bayonetta",
    title: "Bayonetta",
    synopsis:
      "Bruxa Umbra desafia anjos em combate acrobático e over-the-top.",
    steamAppId: 460790,
    releaseYear: 2009,
    genres: ["Ação", "Hack and Slash", "Stylish"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 90,
  },
  {
    slug: "metal-gear-solid-v",
    title: "Metal Gear Solid V: The Phantom Pain",
    synopsis:
      "Stealth tático em mundo aberto — Venom Snake reconstrói a Outer Heaven.",
    steamAppId: 287700,
    releaseYear: 2015,
    genres: ["Stealth", "Ação", "Open World"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 93,
  },
  {
    slug: "hitman-3",
    title: "HITMAN 3",
    synopsis:
      "Assassinato criativo em sandbox como Agente 47 em locações globais.",
    steamAppId: 1659040,
    releaseYear: 2021,
    genres: ["Stealth", "Ação", "Sandbox"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 87,
  },
  {
    slug: "dishonored-2",
    title: "Dishonored 2",
    synopsis:
      "Stealth e poderes sobrenaturais em Karnaca como Corvo ou Emily.",
    steamAppId: 403640,
    releaseYear: 2016,
    genres: ["Stealth", "Ação", "Immersive Sim"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 86,
  },
  {
    slug: "prey",
    title: "Prey",
    synopsis:
      "Immersive sim sci-fi na estação Talos I contra mimics alienígenas.",
    steamAppId: 480490,
    releaseYear: 2017,
    genres: ["FPS", "Immersive Sim", "Horror"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 79,
  },
  {
    slug: "control",
    title: "Control",
    synopsis:
      "Jesse Faden explora o Oldest House e poderes paranormais da Bureau.",
    steamAppId: 870780,
    releaseYear: 2019,
    genres: ["Ação", "Terceira pessoa", "Sci-Fi"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 82,
  },
  {
    slug: "alan-wake-2",
    title: "Alan Wake 2",
    synopsis:
      "Horror psicológico dual entre Alan Wake e Saga Anderson.",
    steamAppId: 1086940,
    releaseYear: 2023,
    genres: ["Horror", "Ação", "Narrativa"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 89,
  },
  {
    slug: "resident-evil-4-remake",
    title: "Resident Evil 4",
    synopsis:
      "Leon Kennedy resgata Ashley em uma aldeia infectada — remake moderno.",
    steamAppId: 2050650,
    releaseYear: 2023,
    genres: ["Survival Horror", "Ação", "Terceira pessoa"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 91,
  },
  {
    slug: "resident-evil-2-remake",
    title: "Resident Evil 2",
    synopsis:
      "Claire e Leon sobrevivem ao apocalipse zumbi em Raccoon City.",
    steamAppId: 883710,
    releaseYear: 2019,
    genres: ["Survival Horror", "Ação", "Terceira pessoa"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 91,
  },
  {
    slug: "silent-hill-2",
    title: "SILENT HILL 2",
    synopsis:
      "James Sunderland busca Mary em Silent Hill — remake psicológico.",
    steamAppId: 2124490,
    releaseYear: 2024,
    genres: ["Horror", "Aventura", "Narrativa"],
    platforms: ["PC", "PlayStation"],
    metacritic: 86,
  },
  {
    slug: "dead-space-remake",
    title: "Dead Space",
    synopsis:
      "Isaac Clarke sobrevive ao USG Ishimura infestado de necromorfos.",
    steamAppId: 1693980,
    releaseYear: 2023,
    genres: ["Survival Horror", "Ação", "Sci-Fi"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 89,
  },
  {
    slug: "the-last-of-us-part-i",
    title: "The Last of Us Part I",
    synopsis:
      "Joel e Ellie atravessam um EUA pós-pandemia em jornada emocional.",
    steamAppId: 1888930,
    releaseYear: 2022,
    genres: ["Ação", "Aventura", "Survival"],
    platforms: ["PC", "PlayStation"],
    metacritic: 88,
  },
  {
    slug: "uncharted-4",
    title: "UNCHARTED: Legacy of Thieves Collection",
    synopsis:
      "Nathan Drake em aventura cinematográfica de tesouros e perseguições.",
    steamAppId: 1659420,
    releaseYear: 2016,
    genres: ["Ação", "Aventura", "Terceira pessoa"],
    platforms: ["PC", "PlayStation"],
    metacritic: 93,
  },
  {
    slug: "titanfall-2",
    title: "Titanfall 2",
    synopsis:
      "Campanha FPS excepcional com parkour e titãs mecha.",
    steamAppId: 1237970,
    releaseYear: 2016,
    genres: ["FPS", "Ação", "Sci-Fi"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 89,
  },
  {
    slug: "doom-eternal",
    title: "DOOM Eternal",
    synopsis:
      "Slayer destrói demônios em ritmo frenético com arsenal brutal.",
    steamAppId: 782330,
    releaseYear: 2020,
    genres: ["FPS", "Ação", "Arena"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 88,
  },
  {
    slug: "doom-2016",
    title: "DOOM",
    synopsis:
      "Reboot clássico do Slayer em Marte — combate puro e visceral.",
    steamAppId: 379720,
    releaseYear: 2016,
    genres: ["FPS", "Ação", "Arena"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 85,
  },
  {
    slug: "wolfenstein-the-new-order",
    title: "Wolfenstein: The New Order",
    synopsis:
      "B.J. Blazkowicz lidera resistência contra o Reich nazista alternativo.",
    steamAppId: 201810,
    releaseYear: 2014,
    genres: ["FPS", "Ação", "Narrativa"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 79,
  },
  {
    slug: "mass-effect-legendary",
    title: "Mass Effect Legendary Edition",
    synopsis:
      "Trilogia remasterizada de Shepard salvando a galáxia da Reapers.",
    steamAppId: 1328670,
    releaseYear: 2021,
    genres: ["RPG", "Ação", "Sci-Fi"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 87,
  },
  {
    slug: "dragon-age-inquisition",
    title: "Dragon Age: Inquisition",
    synopsis:
      "Inquisidor fecha a Breach e unifica Thedas em RPG de escolhas.",
    steamAppId: 1222690,
    releaseYear: 2014,
    genres: ["RPG", "Fantasia", "Ação"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 89,
  },
  {
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    synopsis:
      "RPG épico em D&D 5e com liberdade, romance e combate tático.",
    steamAppId: 1086940,
    releaseYear: 2023,
    genres: ["RPG", "Turn-based", "Fantasia"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 96,
  },
  {
    slug: "divinity-original-sin-2",
    title: "Divinity: Original Sin 2",
    synopsis:
      "RPG tático cooperativo com combate elemental e narrativa reativa.",
    steamAppId: 435150,
    releaseYear: 2017,
    genres: ["RPG", "Turn-based", "Co-op"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 93,
  },
  {
    slug: "pillars-of-eternity",
    title: "Pillars of Eternity",
    synopsis:
      "CRPG isométrico inspirado em Baldur's Gate com mundo profundo.",
    steamAppId: 291650,
    releaseYear: 2015,
    genres: ["RPG", "CRPG", "Fantasia"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 89,
  },
  {
    slug: "undertale",
    title: "Undertale",
    synopsis:
      "RPG indie onde misericórdia ou violência definem o destino de todos.",
    steamAppId: 391540,
    releaseYear: 2015,
    genres: ["RPG", "Indie", "Narrativa"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 92,
  },
  {
    slug: "omori",
    title: "OMORI",
    synopsis:
      "RPG psicológico sobre Sunny e um mundo onírico perturbador.",
    steamAppId: 1150690,
    releaseYear: 2020,
    genres: ["RPG", "Indie", "Horror"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 87,
  },
  {
    slug: "cuphead",
    title: "Cuphead",
    synopsis:
      "Run and gun estilo cartoon dos anos 30 com bosses memoráveis.",
    steamAppId: 268910,
    releaseYear: 2017,
    genres: ["Plataforma", "Run and Gun", "Indie"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 88,
  },
  {
    slug: "ori-and-the-blind-forest",
    title: "Ori and the Blind Forest",
    synopsis:
      "Metroidvania emocionante com plataforma fluida e arte deslumbrante.",
    steamAppId: 261570,
    releaseYear: 2015,
    genres: ["Metroidvania", "Plataforma", "Indie"],
    platforms: ["PC", "Xbox", "Switch"],
    metacritic: 88,
  },
  {
    slug: "ori-and-the-will-of-the-wisps",
    title: "Ori and the Will of the Wisps",
    synopsis:
      "Sequência ainda mais polida de Ori em Nibel.",
    steamAppId: 1057090,
    releaseYear: 2020,
    genres: ["Metroidvania", "Plataforma", "Indie"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 90,
  },
  {
    slug: "super-meat-boy",
    title: "Super Meat Boy",
    synopsis:
      "Plataforma hardcore onde cada morte te ensina a ser melhor.",
    steamAppId: 40800,
    releaseYear: 2010,
    genres: ["Plataforma", "Precisão", "Indie"],
    platforms: ["PC", "Console"],
    metacritic: 87,
  },
  {
    slug: "shovel-knight",
    title: "Shovel Knight: Treasure Trove",
    synopsis:
      "Plataforma retro 8-bit com design impecável e nostalgia honesta.",
    steamAppId: 250760,
    releaseYear: 2014,
    genres: ["Plataforma", "Retro", "Indie"],
    platforms: ["PC", "Console", "Switch"],
    metacritic: 89,
  },
  {
    slug: "dead-cells",
    title: "Dead Cells",
    synopsis:
      "Roguelite metroidvania com combate rápido e builds infinitas.",
    steamAppId: 588650,
    releaseYear: 2018,
    genres: ["Roguelite", "Metroidvania", "Ação"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    metacritic: 89,
  },
  {
    slug: "slay-the-spire",
    title: "Slay the Spire",
    synopsis:
      "Deckbuilder roguelike que definiu o gênero com runs viciantes.",
    steamAppId: 646570,
    releaseYear: 2019,
    genres: ["Roguelike", "Deckbuilder", "Estratégia"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    metacritic: 89,
  },
  {
    slug: "inscryption",
    title: "Inscryption",
    synopsis:
      "Card game horror com quebra de quarta parede e mistérios.",
    steamAppId: 1092790,
    releaseYear: 2021,
    genres: ["Roguelike", "Deckbuilder", "Horror"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 92,
  },
  {
    slug: "balatro",
    title: "Balatro",
    synopsis:
      "Poker roguelike viciante com jokers absurdos e combos infinitos.",
    steamAppId: 2379780,
    releaseYear: 2024,
    genres: ["Roguelike", "Cartas", "Indie"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    metacritic: 90,
  },
  {
    slug: "vampire-survivors",
    title: "Vampire Survivors",
    synopsis:
      "Bullet heaven minimalista — sobreviva 30 minutos contra hordas.",
    steamAppId: 1794680,
    releaseYear: 2022,
    genres: ["Roguelike", "Bullet Heaven", "Indie"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    metacritic: 86,
  },
  {
    slug: "rocket-league",
    title: "Rocket League",
    synopsis:
      "Futebol com carros turbo — competição arcade e skill ceiling alto.",
    steamAppId: 252950,
    releaseYear: 2015,
    genres: ["Esporte", "Competitivo", "Arcade"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 86,
  },
  {
    slug: "forza-horizon-5",
    title: "Forza Horizon 5",
    synopsis:
      "Festival de carros no México — liberdade, clima e coleção massiva.",
    steamAppId: 1551360,
    releaseYear: 2021,
    genres: ["Corrida", "Open World", "Simulação"],
    platforms: ["PC", "Xbox"],
    metacritic: 92,
  },
  {
    slug: "gran-turismo-7",
    title: "Gran Turismo 7",
    synopsis:
      "Simulador de corrida com licenças, carros reais e modo campanha.",
    steamAppId: 0,
    releaseYear: 2022,
    genres: ["Corrida", "Simulação", "Esporte"],
    platforms: ["PlayStation", "PC"],
    metacritic: 87,
  },
  {
    slug: "f1-24",
    title: "F1 24",
    synopsis:
      "Simulador oficial da Fórmula 1 com modos carreira e online.",
    steamAppId: 2488620,
    releaseYear: 2024,
    genres: ["Corrida", "Simulação", "Esporte"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 76,
  },
  {
    slug: "street-fighter-6",
    title: "Street Fighter 6",
    synopsis:
      "Luta 2D moderna com World Tour, Drive System e netcode sólido.",
    steamAppId: 1364780,
    releaseYear: 2023,
    genres: ["Luta", "Competitivo", "Arcade"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 92,
  },
  {
    slug: "tekken-8",
    title: "TEKKEN 8",
    synopsis:
      "Luta 3D da Bandai com Heat System e gráficos next-gen.",
    steamAppId: 1778820,
    releaseYear: 2024,
    genres: ["Luta", "Competitivo", "3D"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 90,
  },
  {
    slug: "super-smash-bros-ultimate",
    title: "Super Smash Bros. Ultimate",
    synopsis:
      "Crossover de lutas com elenco massivo da Nintendo e convidados.",
    steamAppId: 0,
    releaseYear: 2018,
    genres: ["Luta", "Party", "Competitivo"],
    platforms: ["Switch"],
    metacritic: 93,
  },
  {
    slug: "zelda-breath-of-the-wild",
    title: "The Legend of Zelda: Breath of the Wild",
    synopsis:
      "Link explora Hyrule livremente — redefine open world adventure.",
    steamAppId: 0,
    releaseYear: 2017,
    genres: ["Aventura", "Open World", "Ação"],
    platforms: ["Switch", "Wii U"],
    metacritic: 97,
  },
  {
    slug: "zelda-tears-of-the-kingdom",
    title: "The Legend of Zelda: Tears of the Kingdom",
    synopsis:
      "Sequência com Ultrahand, Zonai e Hyrule expandido verticalmente.",
    steamAppId: 0,
    releaseYear: 2023,
    genres: ["Aventura", "Open World", "Ação"],
    platforms: ["Switch"],
    metacritic: 96,
  },
  {
    slug: "super-mario-odyssey",
    title: "Super Mario Odyssey",
    synopsis:
      "Mario viaja reinos com Cappy — plataforma 3D criativo e alegre.",
    steamAppId: 0,
    releaseYear: 2017,
    genres: ["Plataforma", "Aventura", "3D"],
    platforms: ["Switch"],
    metacritic: 97,
  },
  {
    slug: "metroid-dread",
    title: "Metroid Dread",
    synopsis:
      "Samus enfrenta EMMI em ZDR — metroidvania 2D tenso e polido.",
    steamAppId: 0,
    releaseYear: 2021,
    genres: ["Metroidvania", "Ação", "Plataforma"],
    platforms: ["Switch"],
    metacritic: 88,
  },
  {
    slug: "animal-crossing-new-horizons",
    title: "Animal Crossing: New Horizons",
    synopsis:
      "Construa sua ilha, decore, visite amigos e viva no ritmo real.",
    steamAppId: 0,
    releaseYear: 2020,
    genres: ["Simulação", "Vida", "Social"],
    platforms: ["Switch"],
    metacritic: 90,
  },
  {
    slug: "pokemon-scarlet-violet",
    title: "Pokémon Scarlet and Violet",
    synopsis:
      "Região Paldea em open world — capture, batalhe e explore livremente.",
    steamAppId: 0,
    releaseYear: 2022,
    genres: ["RPG", "Aventura", "Coleta"],
    platforms: ["Switch"],
    metacritic: 72,
  },
  {
    slug: "fire-emblem-three-houses",
    title: "Fire Emblem: Three Houses",
    synopsis:
      "Professor em Garreg Mach — estratégia tática e laços com alunos.",
    steamAppId: 0,
    releaseYear: 2019,
    genres: ["Estratégia", "Tático", "RPG"],
    platforms: ["Switch"],
    metacritic: 89,
  },
  {
    slug: "xenoblade-chronicles-3",
    title: "Xenoblade Chronicles 3",
    synopsis:
      "Guerra entre Keves e Agnus — JRPG épico com combate em tempo real.",
    steamAppId: 0,
    releaseYear: 2022,
    genres: ["JRPG", "RPG", "Ação"],
    platforms: ["Switch"],
    metacritic: 89,
  },
  {
    slug: "yakuza-like-a-dragon",
    title: "Like a Dragon: Yakuza",
    synopsis:
      "Ichiban Kasuga e RPG turn-based no submundo de Kamurocho.",
    steamAppId: 1235140,
    releaseYear: 2020,
    genres: ["RPG", "JRPG", "Ação"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 84,
  },
  {
    slug: "yakuza-0",
    title: "Yakuza 0",
    synopsis:
      "Origem de Kiryu e Majima em Kamurocho dos anos 80 — história e minigames.",
    steamAppId: 638970,
    releaseYear: 2015,
    genres: ["Ação", "Aventura", "Beat em up"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 85,
  },
  {
    slug: "judgment",
    title: "Judgment",
    synopsis:
      "Advogado Takayuki Yagami investiga crimes em Kamurocho.",
    steamAppId: 2058190,
    releaseYear: 2018,
    genres: ["Ação", "Aventura", "Investigação"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 83,
  },
  {
    slug: "ninja-gaiden-master-collection",
    title: "Ninja Gaiden: Master Collection",
    synopsis:
      "Trilogia de ação hardcore com Ryu Hayabusa — skill puro.",
    steamAppId: 1580780,
    releaseYear: 2021,
    genres: ["Ação", "Hack and Slash", "Hardcore"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 79,
  },
  {
    slug: "armored-core-vi",
    title: "ARMORED CORE VI FIRES OF RUBICON",
    synopsis:
      "Mechas customizáveis em combate acelerado da FromSoftware.",
    steamAppId: 1888160,
    releaseYear: 2023,
    genres: ["Ação", "Mecha", "Soulslike"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 86,
  },
  {
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    synopsis:
      "V vive Night City — RPG de ação futurista com escolhas e estilo.",
    steamAppId: 1091500,
    releaseYear: 2020,
    genres: ["RPG", "Ação", "Open World"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 86,
  },
  {
    slug: "starfield",
    title: "Starfield",
    synopsis:
      "Exploração espacial Bethesda — construa naves e descubra sistemas.",
    steamAppId: 1716740,
    releaseYear: 2023,
    genres: ["RPG", "Sci-Fi", "Open World"],
    platforms: ["PC", "Xbox"],
    metacritic: 83,
  },
  {
    slug: "no-mans-sky",
    title: "No Man's Sky",
    synopsis:
      "Exploração procedural infinita — base, multiplayer e atualizações constantes.",
    steamAppId: 275850,
    releaseYear: 2016,
    genres: ["Exploração", "Sobrevivência", "Sci-Fi"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 77,
  },
  {
    slug: "subnautica",
    title: "Subnautica",
    synopsis:
      "Sobreviva em planeta oceânico alienígena — terror aquático e crafting.",
    steamAppId: 264710,
    releaseYear: 2018,
    genres: ["Sobrevivência", "Exploração", "Horror"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 87,
  },
  {
    slug: "the-forest",
    title: "The Forest",
    synopsis:
      "Sobreviva a canibais em ilha misteriosa enquanto busca seu filho.",
    steamAppId: 242760,
    releaseYear: 2018,
    genres: ["Sobrevivência", "Horror", "Crafting"],
    platforms: ["PC", "PlayStation"],
    metacritic: 76,
  },
  {
    slug: "sons-of-the-forest",
    title: "Sons Of The Forest",
    synopsis:
      "Sequência cooperativa de survival horror em floresta hostil.",
    steamAppId: 1326470,
    releaseYear: 2023,
    genres: ["Sobrevivência", "Horror", "Co-op"],
    platforms: ["PC"],
    metacritic: 84,
  },
  {
    slug: "league-of-legends",
    title: "League of Legends",
    synopsis:
      "MOBA 5v5 competitivo — campeões, lanes e meta eternamente evolutiva.",
    steamAppId: 0,
    releaseYear: 2009,
    genres: ["MOBA", "Competitivo", "Estratégia"],
    platforms: ["PC"],
    metacritic: 78,
  },
  {
    slug: "dota-2",
    title: "Dota 2",
    synopsis:
      "MOBA hardcore da Valve com profundidade tática e The International.",
    steamAppId: 570,
    releaseYear: 2013,
    genres: ["MOBA", "Competitivo", "Estratégia"],
    platforms: ["PC"],
    metacritic: 90,
  },
  {
    slug: "hearthstone",
    title: "Hearthstone",
    synopsis:
      "Card game digital da Blizzard — decks, arenas e expansões regulares.",
    steamAppId: 0,
    releaseYear: 2014,
    genres: ["Cartas", "Estratégia", "Competitivo"],
    platforms: ["PC", "Mobile"],
    metacritic: 88,
  },
  {
    slug: "genshin-impact",
    title: "Genshin Impact",
    synopsis:
      "Action RPG gacha em Teyvat — exploração, elementos e coop.",
    steamAppId: 0,
    releaseYear: 2020,
    genres: ["ARPG", "Gacha", "Open World"],
    platforms: ["PC", "PlayStation", "Mobile"],
    metacritic: 83,
  },
  {
    slug: "honkai-star-rail",
    title: "Honkai: Star Rail",
    synopsis:
      "RPG turn-based gacha da miHoYo em vagões espaciais e trilhos.",
    steamAppId: 0,
    releaseYear: 2023,
    genres: ["RPG", "Turn-based", "Gacha"],
    platforms: ["PC", "PlayStation", "Mobile"],
    metacritic: 80,
  },
  {
    slug: "fortnite",
    title: "Fortnite",
    synopsis:
      "Battle royale, creative e eventos cross-media — fenômeno cultural.",
    steamAppId: 0,
    releaseYear: 2017,
    genres: ["Battle Royale", "Competitivo", "Construção"],
    platforms: ["PC", "Console", "Mobile"],
    metacritic: 81,
  },
  {
    slug: "pubg-battlegrounds",
    title: "PUBG: BATTLEGROUNDS",
    synopsis:
      "Battle royale realista que popularizou o gênero em escala massiva.",
    steamAppId: 578080,
    releaseYear: 2017,
    genres: ["Battle Royale", "FPS", "Competitivo"],
    platforms: ["PC", "Console", "Mobile"],
    metacritic: 86,
  },
  {
    slug: "sea-of-thieves",
    title: "Sea of Thieves",
    synopsis:
      "Piratas cooperativos em mares abertos — loot, PvP e aventuras emergentes.",
    steamAppId: 1172620,
    releaseYear: 2018,
    genres: ["Aventura", "Co-op", "Open World"],
    platforms: ["PC", "Xbox", "PlayStation"],
    metacritic: 69,
  },
  {
    slug: "deep-rock-galactic",
    title: "Deep Rock Galactic",
    synopsis:
      "Anões mineradores vs alienígenas — coop 4P procedural e caótico.",
    steamAppId: 548430,
    releaseYear: 2020,
    genres: ["Co-op", "FPS", "Roguelite"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 85,
  },
  {
    slug: "left-4-dead-2",
    title: "Left 4 Dead 2",
    synopsis:
      "Coop zombie shooter clássico com AI Director e mods infinitos.",
    steamAppId: 550,
    releaseYear: 2009,
    genres: ["FPS", "Co-op", "Zombie"],
    platforms: ["PC", "Xbox"],
    metacritic: 89,
  },
  {
    slug: "payday-2",
    title: "PAYDAY 2",
    synopsis:
      "Assaltos cooperativos estilo Heat — stealth ou all-out assault.",
    steamAppId: 218620,
    releaseYear: 2013,
    genres: ["FPS", "Co-op", "Heist"],
    platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    metacritic: 79,
  },
  {
    slug: "helldivers-2",
    title: "HELLDIVERS 2",
    synopsis:
      "Tiro cooperativo satírico pela Super Earth contra alienígenas.",
    steamAppId: 553850,
    releaseYear: 2024,
    genres: ["Co-op", "Tiro", "Tático"],
    platforms: ["PC", "PlayStation"],
    metacritic: 86,
  },
  {
    slug: "it-takes-two",
    title: "It Takes Two",
    synopsis:
      "Aventura cooperativa obrigatória 2P — criatividade e emoção.",
    steamAppId: 1426210,
    releaseYear: 2021,
    genres: ["Co-op", "Aventura", "Plataforma"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 89,
  },
  {
    slug: "a-way-out",
    title: "A Way Out",
    synopsis:
      "Fuga da prisão cooperativa exclusiva 2P da Hazelight.",
    steamAppId: 1222700,
    releaseYear: 2018,
    genres: ["Co-op", "Aventura", "Narrativa"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 78,
  },
  {
    slug: "returnal",
    title: "Returnal",
    synopsis:
      "Roguelike third-person shooter em loop temporal no PS5/PC.",
    steamAppId: 1649240,
    releaseYear: 2021,
    genres: ["Roguelike", "Tiro", "Sci-Fi"],
    platforms: ["PC", "PlayStation"],
    metacritic: 86,
  },
  {
    slug: "ratchet-clank-rift-apart",
    title: "Ratchet & Clank: Rift Apart",
    synopsis:
      "Plataforma 3D com dimensões e armas absurdas — showcase next-gen.",
    steamAppId: 0,
    releaseYear: 2021,
    genres: ["Plataforma", "Ação", "Aventura"],
    platforms: ["PC", "PlayStation"],
    metacritic: 88,
  },
  {
    slug: "astro-bot",
    title: "Astro Bot",
    synopsis:
      "Plataforma 3D encantador exclusivo PlayStation — referência de level design.",
    steamAppId: 0,
    releaseYear: 2024,
    genres: ["Plataforma", "Aventura", "3D"],
    platforms: ["PlayStation"],
    metacritic: 94,
  },
  {
    slug: "black-myth-wukong",
    title: "Black Myth: Wukong",
    synopsis:
      "Action RPG inspirado em Journey to the West com combate soulslike.",
    steamAppId: 2358720,
    releaseYear: 2024,
    genres: ["Ação", "RPG", "Soulslike"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 82,
  },
  {
    slug: "lies-of-p",
    title: "Lies of P",
    synopsis:
      "Soulslike em Pinóquio gótico — armas modulares e narrativa moral.",
    steamAppId: 1627720,
    releaseYear: 2023,
    genres: ["Ação", "Soulslike", "RPG"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 80,
  },
  {
    slug: "nioh-2",
    title: "Nioh 2",
    synopsis:
      "Soulslike samurai/yokai com builds profundos e loot.",
    steamAppId: 1325200,
    releaseYear: 2020,
    genres: ["Ação", "Soulslike", "RPG"],
    platforms: ["PC", "PlayStation"],
    metacritic: 86,
  },
  {
    slug: "wo-long-fallen-dynasty",
    title: "Wo Long: Fallen Dynasty",
    synopsis:
      "Soulslike em China dos Três Reinos com deflect e magia.",
    steamAppId: 1448440,
    releaseYear: 2023,
    genres: ["Ação", "Soulslike", "RPG"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 79,
  },
  {
    slug: "kingdom-come-deliverance",
    title: "Kingdom Come: Deliverance",
    synopsis:
      "RPG medieval realista — Henry de Skalitz em Boêmia histórica.",
    steamAppId: 379430,
    releaseYear: 2018,
    genres: ["RPG", "Medieval", "Simulação"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 76,
  },
  {
    slug: "kingdom-come-deliverance-2",
    title: "Kingdom Come: Deliverance II",
    synopsis:
      "Sequência expandida com Boêmia ainda mais viva e consequências.",
    steamAppId: 1771300,
    releaseYear: 2025,
    genres: ["RPG", "Medieval", "Open World"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 88,
  },
  {
    slug: "expedition-33",
    title: "Clair Obscur: Expedition 33",
    synopsis:
      "RPG turn-based francês com arte impressionante e combate inovador.",
    steamAppId: 0,
    releaseYear: 2025,
    genres: ["RPG", "Turn-based", "Narrativa"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 91,
  },
  {
    slug: "indiana-jones-great-circle",
    title: "Indiana Jones and the Great Circle",
    synopsis:
      "Aventura em primeira pessoa com Indy desvendando mistérios globais.",
    steamAppId: 2677660,
    releaseYear: 2024,
    genres: ["Aventura", "Ação", "Narrativa"],
    platforms: ["PC", "Xbox"],
    metacritic: 86,
  },
  {
    slug: "marvel-rivals",
    title: "Marvel Rivals",
    synopsis:
      "Hero shooter 6v6 com elenco Marvel e habilidades espetaculares.",
    steamAppId: 2767030,
    releaseYear: 2024,
    genres: ["Hero Shooter", "Competitivo", "Co-op"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 79,
  },
  {
    slug: "palworld",
    title: "Palworld",
    synopsis:
      "Sobrevivência com criaturas colecionáveis — Pokémon meets crafting.",
    steamAppId: 1623730,
    releaseYear: 2024,
    genres: ["Sobrevivência", "Crafting", "Co-op"],
    platforms: ["PC", "Xbox"],
    metacritic: 73,
  },
  {
    slug: "enshrouded",
    title: "Enshrouded",
    synopsis:
      "Survival action RPG voxel com base building e coop.",
    steamAppId: 1203620,
    releaseYear: 2024,
    genres: ["Sobrevivência", "RPG", "Co-op"],
    platforms: ["PC"],
    metacritic: 76,
  },
  {
    slug: "lies-of-p-overture",
    title: "Lies of P: Overture",
    synopsis:
      "DLC prequel de Lies of P com novas armas e bosses desafiadores.",
    steamAppId: 2848330,
    releaseYear: 2025,
    genres: ["Ação", "Soulslike", "DLC"],
    platforms: ["PC", "PlayStation", "Xbox"],
    metacritic: 82,
  },
].map((game) => ({
  ...game,
  coverUrl:
    game.steamAppId > 0
      ? steamCover(game.steamAppId)
      : `https://placehold.co/460x215/05040a/00f5ff?text=${encodeURIComponent(game.title.slice(0, 20))}`,
}));

export function getSeedGameCount() {
  return seedGames.length;
}
